create table if not exists patients (
 id bigint generated by default as identity primary key,
 patient_id text unique not null,
 name text not null,
 exercise text default 'Full Body Rehabilitation',
 status text default 'Active',
 created_at timestamptz default now()
);

create table if not exists sensor_data (
 id bigint generated by default as identity primary key,
 patient_id text not null,
 torso_imu numeric,
 shoulder_imu numeric,
 left_wrist_imu numeric,
 right_wrist_imu numeric,
 left_elbow_imu numeric,
 right_elbow_imu numeric,
 left_knee_angle numeric,
 right_knee_angle numeric,
 left_ankle_imu numeric,
 right_ankle_imu numeric,
 semg_activity numeric,
 timestamp timestamptz default now()
);

create table if not exists exercise_sessions (
 id bigint generated by default as identity primary key,
 patient_id text not null,
 exercise_name text,
 target_repetitions integer default 10,
 completed_repetitions integer default 0,
 correct_repetitions integer default 0,
 incorrect_repetitions integer default 0,
 accuracy numeric,
 started_at timestamptz default now(),
 completed_at timestamptz
);

create table if not exists ai_feedback (
 id bigint generated by default as identity primary key,
 patient_id text not null,
 body_region text,
 movement_status text,
 risk_level text,
 message text,
 recommendation text,
 created_at timestamptz default now()
);

create table if not exists progress (
 id bigint generated by default as identity primary key,
 patient_id text not null,
 date date default current_date,
 accuracy numeric,
 posture_score numeric,
 upper_body_score numeric,
 lower_body_score numeric,
 overall_score numeric
);

insert into patients (patient_id,name,exercise,status)
values ('Patient 001','Demo Patient','Full Body Rehabilitation','Active')
on conflict (patient_id) do nothing;

alter table patients enable row level security;
alter table sensor_data enable row level security;
alter table exercise_sessions enable row level security;
alter table ai_feedback enable row level security;
alter table progress enable row level security;

create policy "demo read patients" on patients for select to anon using (true);
create policy "demo read sensors" on sensor_data for select to anon using (true);
create policy "demo insert sensors" on sensor_data for insert to anon with check (true);
create policy "demo read sessions" on exercise_sessions for select to anon using (true);
create policy "demo insert sessions" on exercise_sessions for insert to anon with check (true);
create policy "demo read feedback" on ai_feedback for select to anon using (true);
create policy "demo insert feedback" on ai_feedback for insert to anon with check (true);
create policy "demo read progress" on progress for select to anon using (true);
create policy "demo insert progress" on progress for insert to anon with check (true);
